"""Seed data for LCE-WAI: 12 Camper-to-Classroom projects."""

MODULES = [
    {
        "order": 1,
        "slug": "safety-loto",
        "title": "Electrical Safety & Lockout/Tagout Fundamentals",
        "summary": "Build a culture of safety first. Learn OSHA fundamentals, PPE, hazard recognition, and the LOTO procedure before touching a single wire.",
        "objectives": [
            "Identify the four categories of electrical hazards: shock, arc flash, arc blast, and fall",
            "Select and inspect correct PPE (Class 0 gloves, safety glasses, FR clothing)",
            "Perform a six-step Lockout/Tagout procedure on a simulated panel",
            "Read and interpret NFPA 70E arc flash boundary labels",
        ],
        "safety": [
            "Never work energized — verify dead with a known-good tester (test-verify-test)",
            "One lock, one person, one key. No exceptions",
            "Stand to the side of panel doors when operating breakers",
        ],
        "tools": ["Class 0 insulated gloves", "Non-contact voltage tester", "Padlock & tag kit", "Safety glasses (Z87.1)", "Arc-rated long sleeve shirt"],
        "scripture": {"ref": "Proverbs 27:12", "text": "The prudent see danger and take refuge, but the simple keep going and pay the penalty."},
        "tasks": [
            "Walk a partner through hazard identification on a mock job site",
            "Demonstrate test-verify-test on a 120V receptacle (de-energized)",
            "Complete a six-step LOTO cycle and log entry",
        ],
        "competencies": ["ppe-selection", "loto-procedure", "hazard-id"],
        "hours": 8,
    },
    {
        "order": 2,
        "slug": "tools-materials",
        "title": "Tools, Materials & Apprentice Kit Setup",
        "summary": "Every journeyman is only as sharp as the tools in their pouch. Identify and maintain the core hand tools, meters, and consumables you'll use every day.",
        "objectives": [
            "Identify 25 core electrician hand tools by name and function",
            "Set up, zero, and read a digital multimeter (DMM) in AC/DC/continuity modes",
            "Stock and organize a personal tool pouch to code",
        ],
        "safety": ["Inspect insulated tools for cracks before each use", "Never use a steel tape measure near energized bus"],
        "tools": ["Linesman pliers", "Wire strippers", "DMM (CAT III 600V)", "Torque screwdriver", "Conduit reamer"],
        "scripture": {"ref": "Proverbs 22:29", "text": "Do you see someone skilled in their work? They will serve before kings."},
        "tasks": [
            "Pass a timed tool-identification round (25 tools, under 3 minutes)",
            "Measure battery voltage, outlet voltage, and continuity with a DMM",
            "Submit a photo of your organized apprentice pouch",
        ],
        "competencies": ["tool-id", "dmm-use"],
        "hours": 6,
    },
    {
        "order": 3,
        "slug": "dc-fundamentals",
        "title": "DC Circuit Fundamentals",
        "summary": "Ohm's Law is the backbone of the trade. Build series, parallel, and series-parallel DC circuits using batteries and lamps.",
        "objectives": [
            "Apply Ohm's Law (V=IR) and Watt's Law (P=IV) to solve circuit problems",
            "Measure voltage drop across components in series and parallel",
            "Trace current flow on a schematic",
        ],
        "safety": ["Observe polarity on DC sources", "Keep battery terminals covered to prevent short circuits"],
        "tools": ["12V deep-cycle battery", "12V LED lamps (3)", "Alligator leads", "DMM", "Breadboard"],
        "scripture": {"ref": "Ecclesiastes 4:12", "text": "A cord of three strands is not quickly broken."},
        "tasks": [
            "Build a 3-lamp series circuit; record voltage drops",
            "Build a 3-lamp parallel circuit; record branch currents",
            "Solve 5 Ohm's Law word problems",
        ],
        "competencies": ["ohms-law", "dc-circuits"],
        "hours": 10,
    },
    {
        "order": 4,
        "slug": "ac-fundamentals",
        "title": "AC Circuit Fundamentals",
        "summary": "From the utility transformer to the receptacle, understand single-phase and split-phase AC, RMS vs peak, frequency, and service entrance basics.",
        "objectives": [
            "Distinguish peak, peak-to-peak, and RMS values",
            "Explain 120/240V split-phase residential service",
            "Calculate apparent, real, and reactive power",
        ],
        "safety": ["Assume AC conductors are energized until proven otherwise", "Never backfeed a generator without an approved transfer switch"],
        "tools": ["Clamp meter (AC)", "120V test load", "Wiring diagram set", "Torque screwdriver"],
        "scripture": {"ref": "Isaiah 40:29", "text": "He gives strength to the weary and increases the power of the weak."},
        "tasks": [
            "Measure RMS voltage at a standard outlet (de-energized teaching station)",
            "Draw a labeled split-phase service diagram",
            "Complete 10 AC power calculation problems",
        ],
        "competencies": ["ac-theory", "service-entrance"],
        "hours": 10,
    },
    {
        "order": 5,
        "slug": "wiring-splices",
        "title": "Wiring Basics: Splices, Terminations & Conductors",
        "summary": "A clean splice lasts 40 years. A sloppy one starts fires. Master NEC-compliant splices, terminations, and conductor selection.",
        "objectives": [
            "Select the correct conductor size per NEC 310.16 ampacity tables",
            "Make code-compliant wire nut, Wago, and crimp splices",
            "Torque terminations to manufacturer spec",
        ],
        "safety": ["No splice outside an approved box", "Listed connectors only — no tape-only splices"],
        "tools": ["Wire strippers", "Wire nuts (red/yellow/orange)", "Wago lever-nuts", "Torque screwdriver (inch-lbs)"],
        "scripture": {"ref": "Colossians 3:23", "text": "Whatever you do, work at it with all your heart, as working for the Lord."},
        "tasks": [
            "Make 5 pigtail splices in a 4-square box with 12 AWG THHN",
            "Terminate 6 screw-clamp receptacles to torque spec",
            "Pass a pull-test (15 lb) on every splice",
        ],
        "competencies": ["splicing", "terminations", "conductor-selection"],
        "hours": 12,
    },
    {
        "order": 6,
        "slug": "switches-receptacles",
        "title": "Switches, Receptacles & Lighting Circuits",
        "summary": "Wire single-pole, three-way, and four-way switch configurations. Install GFCI and AFCI protection where code requires.",
        "objectives": [
            "Wire single-pole, three-way, and four-way switch circuits",
            "Install and test GFCI/AFCI receptacles",
            "Apply NEC 210 requirements for receptacle placement",
        ],
        "safety": ["Test GFCI monthly with the built-in button", "Confirm grounding continuity before energizing"],
        "tools": ["Receptacle tester", "GFCI tester", "Voltage tester", "Wire strippers"],
        "scripture": {"ref": "Matthew 5:16", "text": "Let your light shine before others."},
        "tasks": [
            "Wire a three-way switch controlling a luminaire from two locations",
            "Install and trip-test a GFCI receptacle",
            "Pass a receptacle-tester check on all installed outlets",
        ],
        "competencies": ["switch-wiring", "gfci-afci"],
        "hours": 12,
    },
    {
        "order": 7,
        "slug": "subpanel-load-calc",
        "title": "Subpanel Installation & Load Calculations",
        "summary": "Size and install a 100A subpanel for the mobile classroom. Perform an NEC 220 load calculation and bend the feeders.",
        "objectives": [
            "Perform a standard NEC 220 dwelling load calculation",
            "Select feeder conductors and overcurrent protection",
            "Install a 100A subpanel with separated neutrals and grounds",
        ],
        "safety": ["Neutrals and grounds bonded ONLY at service disconnect", "Torque all lugs to label spec"],
        "tools": ["100A load center", "2 AWG THHN feeder", "Main lug kit", "Torque wrench"],
        "scripture": {"ref": "Luke 14:28", "text": "Suppose one of you wants to build a tower. Won't you first sit down and estimate the cost?"},
        "tasks": [
            "Complete a written load calculation worksheet for the camper",
            "Mount and land feeders on a 100A subpanel",
            "Verify separation of grounded and grounding conductors",
        ],
        "competencies": ["load-calc", "subpanel-install"],
        "hours": 14,
    },
    {
        "order": 8,
        "slug": "conduit-bending",
        "title": "Conduit Bending & Raceway Installation",
        "summary": "Learn 90s, offsets, saddles, and concentric bends in EMT. Hand benders only — precision is the point.",
        "objectives": [
            "Bend accurate 90°, offset, and 3-point saddle bends in 1/2\" and 3/4\" EMT",
            "Calculate shrink, gain, and developed length",
            "Support and secure raceway per NEC 358",
        ],
        "safety": ["Ream all cut ends", "Secure EMT within 3 ft of every box"],
        "tools": ["Hand bender (1/2\" and 3/4\")", "Tape measure", "Reamer", "Tubing cutter"],
        "scripture": {"ref": "Isaiah 40:4", "text": "Every valley shall be raised up, every mountain and hill made low; the rough ground shall become level."},
        "tasks": [
            "Bend a 22.5° offset with 6\" rise in 3/4\" EMT (±1/16\" tolerance)",
            "Complete a 4-bend parallel saddle between two points",
            "Install a 10 ft EMT run with supports at code spacing",
        ],
        "competencies": ["conduit-bending", "raceway-install"],
        "hours": 16,
    },
    {
        "order": 9,
        "slug": "grounding-bonding",
        "title": "Grounding & Bonding",
        "summary": "The most misunderstood — and most important — system in the building. Drive a ground rod, bond a service, and prove continuity.",
        "objectives": [
            "Distinguish grounded (neutral), grounding, and bonding conductors",
            "Install a grounding electrode system per NEC 250",
            "Measure ground resistance with a clamp-on ground tester",
        ],
        "safety": ["Never cut the grounding conductor under load", "Bond all metallic enclosures"],
        "tools": ["8 ft copper ground rod", "Acorn clamp", "#6 bare copper GEC", "Clamp-on ground resistance tester"],
        "scripture": {"ref": "Matthew 7:25", "text": "The house on the rock did not fall, because it had its foundation on the rock."},
        "tasks": [
            "Drive a ground rod and connect with an acorn clamp",
            "Bond all metallic raceways in the camper classroom",
            "Record measured ground resistance (target <25Ω)",
        ],
        "competencies": ["grounding", "bonding"],
        "hours": 10,
    },
    {
        "order": 10,
        "slug": "solar-design",
        "title": "Off-Grid Solar PV System Design",
        "summary": "Design a 48V off-grid solar array sized for the mobile classroom's daily load. Learn sun hours, tilt angle, and string sizing.",
        "objectives": [
            "Calculate daily watt-hour loads and design a PV array to match",
            "Size conductors and overcurrent protection for DC PV strings",
            "Select components: panels, charge controller, inverter, battery bank",
        ],
        "safety": ["PV arrays are energized by sunlight — cover or disconnect before servicing", "DC arc faults do not self-extinguish"],
        "tools": ["Solar irradiance meter", "DMM (CAT III 1000V DC)", "Load calc worksheet"],
        "scripture": {"ref": "Genesis 1:16", "text": "God made two great lights—the greater light to govern the day."},
        "tasks": [
            "Complete a daily kWh load worksheet for the camper",
            "Size a 48V PV string and select panels to match",
            "Draw a full single-line diagram of the PV system",
        ],
        "competencies": ["solar-design", "dc-sizing"],
        "hours": 14,
    },
    {
        "order": 11,
        "slug": "battery-inverter",
        "title": "Battery Bank, Inverter & Charge Controller Wiring",
        "summary": "Build the power heart of the mobile classroom: LiFePO4 bank, MPPT controller, and pure sine inverter, all safely fused and bonded.",
        "objectives": [
            "Wire a 48V LiFePO4 battery bank with class-T fusing",
            "Terminate DC cables with hydraulic crimp lugs to manufacturer spec",
            "Configure MPPT charge controller and inverter parameters",
        ],
        "safety": ["Always fuse within 7\" of the battery positive terminal", "Remove rings and watches before working on battery bus"],
        "tools": ["Hydraulic crimper", "Class-T fuse & holder", "Torque wrench (ft-lbs)", "MPPT controller"],
        "scripture": {"ref": "2 Timothy 1:7", "text": "God has not given us a spirit of fear, but of power, love, and a sound mind."},
        "tasks": [
            "Crimp and heat-shrink four 4/0 battery cables",
            "Install class-T fuses at the battery positive",
            "Commission the MPPT and inverter, log firmware version",
        ],
        "competencies": ["battery-wiring", "inverter-config"],
        "hours": 14,
    },
    {
        "order": 12,
        "slug": "commissioning",
        "title": "Final Integration: Mobile Classroom Commissioning & Testing",
        "summary": "Capstone. Bring the full camper-to-classroom online: load test every circuit, verify protection, and present to the associate.",
        "objectives": [
            "Execute a written commissioning checklist on the full system",
            "Load-test every branch circuit at rated amperage",
            "Present your work to instructors and a visiting journeyman",
        ],
        "safety": ["Commissioning is performed energized — buddy system and full PPE only", "Stop work and report any abnormal heat, smell, or sound"],
        "tools": ["Clamp meter", "Insulation resistance tester (megger)", "Load bank", "Commissioning checklist"],
        "scripture": {"ref": "2 Timothy 4:7", "text": "I have fought the good fight, I have finished the race, I have kept the faith."},
        "tasks": [
            "Megger every branch circuit (>1 MΩ required)",
            "Load-test every circuit to 80% of breaker rating for 3 minutes",
            "Present commissioning report and receive sign-off",
        ],
        "competencies": ["commissioning", "system-integration"],
        "hours": 16,
    },
]


def quiz_for(module_slug: str):
    """Return a seed quiz (4 questions) for each module."""
    bank = {
        "safety-loto": [
            {"q": "Which NFPA standard covers Electrical Safety in the Workplace?", "options": ["NFPA 13", "NFPA 70", "NFPA 70E", "NFPA 101"], "answer": 2},
            {"q": "The correct PPE verification sequence is:", "options": ["Work-Test-Work", "Test-Verify-Test", "Verify-Work-Verify", "Test-Work-Test"], "answer": 1},
            {"q": "In LOTO, how many locks per worker on the device?", "options": ["One per worker, with their own key", "One shared lock", "As many as you want", "None if supervised"], "answer": 0},
            {"q": "Arc-rated clothing is rated in:", "options": ["PSI", "cal/cm²", "kV", "Amps"], "answer": 1},
        ],
        "tools-materials": [
            {"q": "A CAT III 600V multimeter is rated for:", "options": ["Battery work only", "Distribution-level measurements", "Utility transmission", "Signal-level electronics"], "answer": 1},
            {"q": "Which tool strips insulation without nicking the conductor?", "options": ["Side cutters", "Wire strippers", "Utility knife", "Linesman pliers"], "answer": 1},
            {"q": "Before each use, insulated tools should be:", "options": ["Oiled", "Sharpened", "Inspected for cracks", "Painted"], "answer": 2},
            {"q": "A torque screwdriver is used to:", "options": ["Strip wire", "Apply rated tightness", "Cut conduit", "Measure voltage"], "answer": 1},
        ],
        "dc-fundamentals": [
            {"q": "Ohm's Law states:", "options": ["P = IV", "V = IR", "R = P/I", "I = V²/R"], "answer": 1},
            {"q": "In a series circuit, current is:", "options": ["Different at each point", "The same at every point", "Zero", "Doubled"], "answer": 1},
            {"q": "Three 10Ω resistors in parallel have total resistance of:", "options": ["30Ω", "10Ω", "3.33Ω", "1Ω"], "answer": 2},
            {"q": "Power in watts equals:", "options": ["V × I", "V / I", "I / V", "V + I"], "answer": 0},
        ],
        "ac-fundamentals": [
            {"q": "Standard US residential service is:", "options": ["120V three-phase", "240V three-phase", "120/240V split-phase", "480V delta"], "answer": 2},
            {"q": "RMS voltage of a 170V peak sine wave is:", "options": ["85V", "120V", "170V", "240V"], "answer": 1},
            {"q": "US grid frequency is:", "options": ["50 Hz", "60 Hz", "400 Hz", "100 Hz"], "answer": 1},
            {"q": "Apparent power is measured in:", "options": ["Watts", "VAR", "VA", "Henries"], "answer": 2},
        ],
        "wiring-splices": [
            {"q": "Splices must be made inside a(n):", "options": ["Approved box", "Wall cavity", "Attic", "Any dry location"], "answer": 0},
            {"q": "15A branch circuit minimum conductor size is:", "options": ["18 AWG", "16 AWG", "14 AWG", "12 AWG"], "answer": 2},
            {"q": "Terminations should be tightened to:", "options": ["As tight as possible", "Manufacturer's torque spec", "Hand tight", "Until it clicks"], "answer": 1},
            {"q": "Wago lever-nut connectors are:", "options": ["Unlisted", "Listed connectors for code splices", "Only for DC", "Only for aluminum"], "answer": 1},
        ],
        "switches-receptacles": [
            {"q": "A three-way switch has how many traveler terminals?", "options": ["1", "2", "3", "4"], "answer": 1},
            {"q": "GFCI receptacles protect against:", "options": ["Overload", "Short circuit", "Ground fault / shock", "Arc faults only"], "answer": 2},
            {"q": "GFCI is required in:", "options": ["Bedrooms only", "Bathrooms, kitchens, outdoors, garages", "Attics", "Living rooms"], "answer": 1},
            {"q": "AFCI protects against:", "options": ["Ground faults", "Parallel/series arcing faults", "Overvoltage", "Short circuits only"], "answer": 1},
        ],
        "subpanel-load-calc": [
            {"q": "In a subpanel, neutrals and grounds must be:", "options": ["Bonded together", "Kept separate", "Connected to conduit only", "Floating"], "answer": 1},
            {"q": "NEC 220 governs:", "options": ["Grounding", "Load calculations", "Conduit fill", "Motor circuits"], "answer": 1},
            {"q": "A 100A feeder typically uses (Cu THHN):", "options": ["14 AWG", "10 AWG", "3 AWG", "4/0 AWG"], "answer": 2},
            {"q": "The main bonding jumper is located at:", "options": ["Every subpanel", "The service disconnect only", "Each branch circuit", "The meter base"], "answer": 1},
        ],
        "conduit-bending": [
            {"q": "Shrink per inch of offset for a 30° bend is approximately:", "options": ["1/8\"", "1/4\"", "1/2\"", "1\""], "answer": 1},
            {"q": "EMT must be supported within how many feet of a box?", "options": ["3 ft", "5 ft", "8 ft", "10 ft"], "answer": 0},
            {"q": "After cutting EMT, you must:", "options": ["Paint it", "Ream it", "Thread it", "Ground it"], "answer": 1},
            {"q": "A concentric bend has:", "options": ["A single radius", "Multiple radii sharing a center", "No radius", "Two 90s"], "answer": 1},
        ],
        "grounding-bonding": [
            {"q": "Target resistance for a single ground rod per NEC 250.56 is:", "options": ["<1Ω", "<25Ω", "<100Ω", "No limit"], "answer": 1},
            {"q": "The grounding electrode conductor connects:", "options": ["Neutral to load", "Service neutral to the electrode", "Hot to ground", "Load to breaker"], "answer": 1},
            {"q": "Bonding ensures:", "options": ["Low impedance path for fault current", "Higher voltage", "Lower amperage", "Better insulation"], "answer": 0},
            {"q": "A typical driven ground rod is:", "options": ["4 ft", "6 ft", "8 ft", "12 ft"], "answer": 2},
        ],
        "solar-design": [
            {"q": "Daily energy is measured in:", "options": ["kW", "kWh", "VA", "Ah"], "answer": 1},
            {"q": "Peak sun hours is:", "options": ["Hours between sunrise and sunset", "Equivalent hours at 1000 W/m²", "Latitude", "Solar azimuth"], "answer": 1},
            {"q": "An MPPT controller:", "options": ["Tracks maximum power point of the array", "Only charges at 12V", "Increases panel wattage", "Replaces the inverter"], "answer": 0},
            {"q": "A 48V bank is preferred over 12V for larger systems because:", "options": ["It's cheaper", "Lower current, smaller conductors, less loss", "Simpler wiring", "Required by code"], "answer": 1},
        ],
        "battery-inverter": [
            {"q": "Battery fuses should be placed:", "options": ["Anywhere in the circuit", "Within 7\" of battery positive", "At the inverter", "At the load"], "answer": 1},
            {"q": "Pure sine wave inverters are required for:", "options": ["Resistive loads only", "Sensitive electronics and motors", "DC loads", "Lighting only"], "answer": 1},
            {"q": "LiFePO4 batteries require:", "options": ["No BMS", "A battery management system (BMS)", "Flooded vent caps", "A hydrometer"], "answer": 1},
            {"q": "Torque on battery lugs should be:", "options": ["Hand tight", "Per manufacturer spec", "As tight as possible", "Not critical"], "answer": 1},
        ],
        "commissioning": [
            {"q": "A megger tests:", "options": ["Insulation resistance", "Continuity only", "AC voltage", "DC amperage"], "answer": 0},
            {"q": "Minimum acceptable insulation resistance (general rule):", "options": ["1 kΩ", "10 kΩ", "1 MΩ", "1 GΩ"], "answer": 2},
            {"q": "Load testing verifies:", "options": ["Branch circuits carry rated current safely", "The paint job", "Conduit length", "Box fill"], "answer": 0},
            {"q": "Commissioning sign-off requires:", "options": ["Only student signature", "Instructor + qualified journeyman", "No sign-off needed", "Homeowner only"], "answer": 1},
        ],
    }
    return bank.get(module_slug, [])
