"""W.A.I. credential definitions. Auto-award triggers are evaluated after quiz/lab events."""

CREDENTIALS = [
    {
        "key": "level-1-graduate",
        "name": "Level 1 — Apprentice Foundations",
        "description": "Completed the foundational safety, circuits, and wiring modules of the Camper-to-Classroom curriculum.",
        "category": "level",
        "evidence": "Modules 01–04 passed with 70%+",
        "image": None,
        "expires_months": None,
        "trigger": {"type": "modules_all_of", "slugs": ["safety-loto", "tools-materials", "dc-fundamentals", "ac-fundamentals"]},
        "tags": ["level-1", "foundations"],
    },
    {
        "key": "level-2-graduate",
        "name": "Level 2 — Residential Wiring",
        "description": "Completed wiring, switches, subpanel, and conduit modules.",
        "category": "level",
        "evidence": "Modules 05–08 passed with 70%+",
        "expires_months": None,
        "trigger": {"type": "modules_all_of", "slugs": ["wiring-splices", "switches-receptacles", "subpanel-load-calc", "conduit-bending"]},
        "tags": ["level-2", "residential"],
    },
    {
        "key": "level-3-graduate",
        "name": "Level 3 — Grounding, Solar & Commissioning",
        "description": "Completed grounding, solar design, battery & commissioning modules.",
        "category": "level",
        "evidence": "Modules 09–12 passed with 70%+",
        "expires_months": None,
        "trigger": {"type": "modules_all_of", "slugs": ["grounding-bonding", "solar-design", "battery-inverter", "commissioning"]},
        "tags": ["level-3", "advanced"],
    },
    {
        "key": "program-graduate",
        "name": "W.A.I. Program Graduate",
        "description": "Completed all 12 Camper-to-Classroom modules with passing scores.",
        "category": "capstone",
        "evidence": "All 12 modules passed",
        "expires_months": None,
        "trigger": {"type": "all_modules"},
        "tags": ["capstone", "graduate"],
    },
    {
        "key": "safety-ppe-certified",
        "name": "Safety & PPE Certified",
        "description": "Demonstrated mastery in PPE selection, hazard recognition, and electrical safety fundamentals.",
        "category": "skill",
        "evidence": "Safety & PPE competency reached 100 skill points",
        "expires_months": 12,
        "trigger": {"type": "competency_at_least", "key": "safety-ppe", "points": 100},
        "tags": ["safety", "ppe"],
    },
    {
        "key": "wiring-fundamentals-badge",
        "name": "Wiring Fundamentals Badge",
        "description": "Demonstrated competency in splicing, terminations, and conductor selection.",
        "category": "skill",
        "evidence": "Wiring Fundamentals competency reached 100 points",
        "expires_months": None,
        "trigger": {"type": "competency_at_least", "key": "wiring-fundamentals", "points": 100},
        "tags": ["wiring"],
    },
    {
        "key": "conduit-bending-badge",
        "name": "Conduit & Bending Badge",
        "description": "Precision bending of 90°, offsets, and saddles in EMT.",
        "category": "skill",
        "evidence": "Conduit & Bending competency reached 100 points",
        "expires_months": None,
        "trigger": {"type": "competency_at_least", "key": "conduit-bending", "points": 100},
        "tags": ["conduit"],
    },
    {
        "key": "panels-breakers-badge",
        "name": "Panels & Breakers Badge",
        "description": "Load center installation, breaker termination, and NEC load calculations.",
        "category": "skill",
        "evidence": "Panels & Breakers competency reached 100 points",
        "expires_months": None,
        "trigger": {"type": "competency_at_least", "key": "panels-breakers", "points": 100},
        "tags": ["panel"],
    },
    {
        "key": "troubleshooting-badge",
        "name": "Troubleshooting Badge",
        "description": "Systematic fault isolation and meter-based diagnostics.",
        "category": "skill",
        "evidence": "Troubleshooting competency reached 100 points",
        "expires_months": None,
        "trigger": {"type": "competency_at_least", "key": "troubleshooting", "points": 100},
        "tags": ["troubleshooting"],
    },
    {
        "key": "solar-off-grid-badge",
        "name": "Solar & Off-Grid Badge",
        "description": "PV sizing, MPPT controller, and battery/inverter configuration.",
        "category": "skill",
        "evidence": "Solar & Off-Grid competency reached 100 points",
        "expires_months": None,
        "trigger": {"type": "competency_at_least", "key": "solar-off-grid", "points": 100},
        "tags": ["solar"],
    },
    {
        "key": "loto-certified",
        "name": "LOTO Certified",
        "description": "Certified to execute Lockout/Tagout procedures on real equipment. 6-month renewal required.",
        "category": "compliance",
        "evidence": "Passed LOTO online scenario AND in-person LOTO lab",
        "expires_months": 6,
        "trigger": {"type": "labs_all_of", "slugs": ["loto-scenario", "loto-real-equipment"]},
        "tags": ["loto", "compliance", "safety"],
    },
    {
        "key": "osha-10-awareness",
        "name": "OSHA 10 Awareness (Electrical)",
        "description": "Completed OSHA 10 awareness content tied to the safety module.",
        "category": "compliance",
        "evidence": "Passed Safety & LOTO module with 70%+",
        "expires_months": 36,
        "trigger": {"type": "module_completed", "slug": "safety-loto"},
        "tags": ["osha", "compliance"],
    },
    {
        "key": "nfpa-70e-awareness",
        "name": "NFPA 70E Awareness",
        "description": "Workplace electrical safety awareness aligned to NFPA 70E.",
        "category": "compliance",
        "evidence": "Passed Safety & LOTO module + Safety PPE competency ≥ 50",
        "expires_months": 12,
        "trigger": {"type": "competency_at_least", "key": "safety-ppe", "points": 50},
        "tags": ["nfpa", "70e"],
    },
    {
        "key": "solar-installer-l1",
        "name": "Solar PV Installer Level 1",
        "description": "Can safely mount, wire, and commission a small off-grid PV array.",
        "category": "skill",
        "evidence": "Passed solar mount + charge controller + battery inverter labs",
        "expires_months": None,
        "trigger": {"type": "labs_all_of", "slugs": ["solar-panel-mount", "solar-charge-controller", "battery-inverter-build"]},
        "tags": ["solar", "installer"],
    },
]
