"""LCE-WAI Labs seed: 9 online + 12 in-person + 8 competencies.

Online labs each declare a simulator_type keyword the frontend renders.
In-person labs declare a rubric + pass criteria.
"""

COMPETENCIES = [
    {"key": "wiring-fundamentals", "name": "Wiring Fundamentals", "description": "Splicing, terminations, conductor selection, and circuit logic."},
    {"key": "safety-ppe", "name": "Safety & PPE", "description": "Hazard recognition, PPE, LOTO, and NFPA 70E compliance."},
    {"key": "tools-equipment", "name": "Tools & Equipment", "description": "Proper use, inspection, and maintenance of electrician tools and meters."},
    {"key": "conduit-bending", "name": "Conduit & Bending", "description": "EMT and raceway installation, precise 90s, offsets, and saddles."},
    {"key": "panels-breakers", "name": "Panels & Breakers", "description": "Load centers, breaker termination, load calculations, GFCI/AFCI."},
    {"key": "troubleshooting", "name": "Troubleshooting", "description": "Systematic fault isolation, continuity and voltage testing, logic."},
    {"key": "solar-off-grid", "name": "Solar & Off-Grid Systems", "description": "PV sizing, charge controllers, battery banks, and inverters."},
    {"key": "professionalism", "name": "Professionalism", "description": "Workmanship, documentation, communication, and jobsite conduct."},
]


ONLINE_LABS = [
    {
        "slug": "basic-circuit-sim",
        "title": "Basic Circuit Builder",
        "simulator_type": "basic_circuit",
        "summary": "Build series and parallel resistor networks and solve for total resistance, current, and voltage drops.",
        "objectives": [
            "Calculate total resistance of series and parallel networks",
            "Apply Ohm's Law to find circuit current",
            "Compute voltage drop across each resistor",
        ],
        "safety": ["This is a simulation — always verify de-energized on real circuits."],
        "steps": ["Enter source voltage", "Enter three resistor values", "Choose configuration (series/parallel)", "Solve and check with the simulator"],
        "competencies": ["wiring-fundamentals", "troubleshooting"],
        "skill_points": 20,
        "hours": 1,
    },
    {
        "slug": "switch-wiring-sim",
        "title": "Switch & Receptacle Wiring",
        "simulator_type": "switch_wiring",
        "summary": "Identify correct conductor connections for single-pole, 3-way, and duplex receptacle installations.",
        "objectives": [
            "Identify hot, neutral, and ground terminals",
            "Wire a single-pole switch loop correctly",
            "Recognize miswires that cause shock or short circuits",
        ],
        "safety": ["Real receptacles must be wired de-energized and ground-continuity tested."],
        "steps": ["Review the diagram", "Select the correct terminal for each conductor", "Submit to auto-grade"],
        "competencies": ["wiring-fundamentals", "safety-ppe"],
        "skill_points": 25,
        "hours": 1,
    },
    {
        "slug": "panel-labeling-sim",
        "title": "Breaker Panel Labeling",
        "simulator_type": "panel_labeling",
        "summary": "Label each breaker slot in a residential panel based on the provided branch circuit list.",
        "objectives": [
            "Map branch circuits to breaker positions",
            "Follow NEC 408.4 legibility requirements",
            "Balance loads across phases",
        ],
        "safety": ["Panel covers off = energized bus exposed. PPE and distance rules apply on real panels."],
        "steps": ["Read the circuit list", "Match each breaker to its circuit", "Submit labels"],
        "competencies": ["panels-breakers", "professionalism"],
        "skill_points": 25,
        "hours": 1,
    },
    {
        "slug": "conduit-bending-calc",
        "title": "Conduit Bending Angle Calculator",
        "simulator_type": "conduit_calc",
        "summary": "Compute shrink, gain, and developed length for offsets and saddles in EMT.",
        "objectives": [
            "Calculate shrink per inch of rise for standard bend angles",
            "Determine distance between marks for an offset",
            "Pick the right bend angle for the obstacle",
        ],
        "safety": ["Deburr every cut end; support within 3 ft of every box on real installs."],
        "steps": ["Enter obstacle height and bend angle", "Read shrink and distance between marks", "Verify against practice bend"],
        "competencies": ["conduit-bending", "tools-equipment"],
        "skill_points": 25,
        "hours": 1,
    },
    {
        "slug": "voltage-drop-calc",
        "title": "Voltage Drop Calculator",
        "simulator_type": "vdrop",
        "summary": "Verify conductor size selection using the NEC voltage-drop formula for one-way feeders and branch circuits.",
        "objectives": [
            "Apply Vdrop = 2·K·I·L / CM formula for single-phase",
            "Select a conductor that keeps drop ≤ 3% on branch circuits",
            "Understand K values for Cu and Al",
        ],
        "safety": ["Low voltage drop protects motors and electronics from damage."],
        "steps": ["Enter length, current, material, and AWG", "Compute drop", "Resize if >3%"],
        "competencies": ["wiring-fundamentals", "troubleshooting"],
        "skill_points": 25,
        "hours": 1,
    },
    {
        "slug": "solar-config-sim",
        "title": "Solar System Configuration",
        "simulator_type": "solar_config",
        "summary": "Size an off-grid array to match a daily load in kWh. Pick panels, controller, battery bank, and inverter.",
        "objectives": [
            "Convert daily load to required PV wattage using peak sun hours",
            "Calculate battery bank amp-hours at a system voltage",
            "Match MPPT controller current to array output",
        ],
        "safety": ["PV arrays are energized any time they see daylight."],
        "steps": ["Enter daily kWh, sun hours, system voltage, days of autonomy", "Review sizing output", "Confirm within tolerance"],
        "competencies": ["solar-off-grid"],
        "skill_points": 30,
        "hours": 2,
    },
    {
        "slug": "loto-scenario",
        "title": "Lockout/Tagout Digital Scenario",
        "simulator_type": "loto",
        "summary": "Walk a six-step LOTO procedure on a simulated motor disconnect. Miss a step and it's a safety fail.",
        "objectives": [
            "Execute the six LOTO steps in correct order",
            "Identify each required PPE item before energization check",
            "Understand one lock, one key, one worker",
        ],
        "safety": ["No shortcuts on real equipment. Lives depend on LOTO."],
        "steps": ["Select steps in order", "Pick PPE for verification", "Verify test-verify-test sequence"],
        "competencies": ["safety-ppe", "professionalism"],
        "skill_points": 30,
        "hours": 1,
    },
    {
        "slug": "troubleshooting-sim",
        "title": "Troubleshooting Logic",
        "simulator_type": "troubleshooting",
        "summary": "A branch circuit has failed. Use decision-tree logic to find the root cause in the fewest checks.",
        "objectives": [
            "Follow a systematic divide-and-conquer approach",
            "Choose the right meter function at each step",
            "Document findings clearly",
        ],
        "safety": ["Assume energized until measured dead."],
        "steps": ["Read the fault description", "Pick your next diagnostic action", "Continue until solved"],
        "competencies": ["troubleshooting", "wiring-fundamentals"],
        "skill_points": 30,
        "hours": 2,
    },
    {
        "slug": "load-balancing-sim",
        "title": "Load Balancing Simulator",
        "simulator_type": "load_balance",
        "summary": "Assign branch circuits across two phases of a 120/240V panel to balance the load within 10%.",
        "objectives": [
            "Calculate total load on each phase",
            "Reassign breakers to balance within 10%",
            "Understand why balanced panels reduce neutral heating",
        ],
        "safety": ["Unbalanced loads overheat neutrals in multi-wire branch circuits."],
        "steps": ["Review circuit list with loads", "Drag or select phase A/B for each circuit", "Submit when balanced"],
        "competencies": ["panels-breakers", "professionalism"],
        "skill_points": 25,
        "hours": 1,
    },
]


IN_PERSON_LABS = [
    {
        "slug": "emt-conduit-install",
        "title": "Install EMT Conduit (½\" and ¾\")",
        "summary": "Cut, ream, bend, and secure a 10-foot EMT run with two boxes, using hand benders only.",
        "tools": ["Hand bender (½\" & ¾\")", "Tubing cutter", "Reamer", "Tape measure", "Level"],
        "materials": ["10 ft ½\" EMT", "10 ft ¾\" EMT", "Connectors, couplings, straps", "4-square and 1-gang boxes"],
        "safety": ["Eye protection for cutting/reaming", "Inspect bender for cracks", "Ream every cut end"],
        "steps": ["Measure and cut EMT", "Ream and deburr", "Bend 90s and offsets per drawing", "Secure within 3 ft of each box", "Mount and land to boxes"],
        "rubric": ["Bends within ±1/16\" tolerance", "Supports at correct intervals", "No burrs or sharp edges", "Boxes plumb and flush"],
        "pass_criteria": "All four rubric items passing + instructor sign-off",
        "competencies": ["conduit-bending", "tools-equipment"],
        "skill_points": 50,
        "hours": 4,
    },
    {
        "slug": "switch-loop-wiring",
        "title": "Wire a Switch Loop",
        "summary": "Install a single-pole switch controlling a luminaire in a switch loop configuration.",
        "tools": ["Wire strippers", "Lineman pliers", "Voltage tester", "Torque screwdriver"],
        "materials": ["12/2 NM-B cable", "Single-pole switch", "Keyless luminaire", "Wire nuts"],
        "safety": ["Circuit off and LOTO", "Verify de-energized", "Re-identify white conductor as hot"],
        "steps": ["De-energize and LOTO", "Pull cable", "Identify white as hot at switch", "Terminate switch and luminaire", "Re-energize and test"],
        "rubric": ["Correct re-identification of neutral-as-hot", "Tight terminations", "Switch operates luminaire", "No open splices"],
        "pass_criteria": "Switch controls fixture AND instructor verifies no code violations",
        "competencies": ["wiring-fundamentals", "safety-ppe"],
        "skill_points": 40,
        "hours": 3,
    },
    {
        "slug": "three-four-way-circuit",
        "title": "3-Way and 4-Way Switch Circuit",
        "summary": "Wire a luminaire controlled from three locations using a 3-way + 4-way + 3-way configuration.",
        "tools": ["Wire strippers", "Lineman pliers", "Voltage tester"],
        "materials": ["14/3 travelers", "3-way switches (2)", "4-way switch (1)", "Luminaire"],
        "safety": ["De-energize and LOTO", "Label travelers before termination"],
        "steps": ["De-energize circuit", "Route 14/3 traveler cables", "Terminate 3-ways at each end", "Terminate 4-way in middle", "Energize and functional test"],
        "rubric": ["Switch from any location operates fixture correctly", "Travelers correctly identified", "Tight terminations", "No miswired hot-to-neutral"],
        "pass_criteria": "All switch combinations work AND clean workmanship",
        "competencies": ["wiring-fundamentals", "troubleshooting"],
        "skill_points": 50,
        "hours": 4,
    },
    {
        "slug": "load-center-install",
        "title": "Install a 100A Load Center",
        "summary": "Mount and land feeders on a 100A load center with separated neutrals and grounds for a subpanel.",
        "tools": ["Torque wrench (inch-lbs)", "Knockout punch", "Level", "Drill"],
        "materials": ["100A load center", "2 AWG THHN feeders", "Main lug kit", "Grounding bus"],
        "safety": ["Feeder disconnect OFF and LOTO", "Wear Class 0 gloves when energized"],
        "steps": ["Mount panel plumb", "Punch knockouts for feeders", "Land feeders per torque spec", "Install ground/neutral isolation for subpanel", "Close cover and label"],
        "rubric": ["Neutrals separated from grounds at subpanel", "Lugs torqued to label", "Knockouts filled or protected", "Panel plumb and labeled"],
        "pass_criteria": "All four rubric items AND load-test on energization",
        "competencies": ["panels-breakers", "professionalism"],
        "skill_points": 60,
        "hours": 6,
    },
    {
        "slug": "breaker-termination",
        "title": "Terminate Branch Circuit Breakers",
        "summary": "Install and torque-terminate 4 branch circuit breakers in the load center from lab 4.",
        "tools": ["Torque screwdriver", "Wire strippers"],
        "materials": ["Single-pole 15A breakers (2)", "Single-pole 20A breakers (2)", "12 AWG THHN"],
        "safety": ["Panel de-energized and LOTO", "Verify with tester"],
        "steps": ["Strip conductor to gauge", "Seat in breaker lug", "Torque to spec", "Snap breaker onto bus", "Label circuit"],
        "rubric": ["Torque at manufacturer spec (±0)", "Conductor fully inserted, no strands out", "Breaker snapped flush", "Circuit clearly labeled"],
        "pass_criteria": "Visual + torque verification AND labeling legible",
        "competencies": ["panels-breakers", "wiring-fundamentals"],
        "skill_points": 40,
        "hours": 3,
    },
    {
        "slug": "gfci-afci-install",
        "title": "Install GFCI and AFCI Devices",
        "summary": "Install a GFCI receptacle at a bathroom location and an AFCI breaker for a bedroom circuit.",
        "tools": ["Wire strippers", "Receptacle tester with GFCI trip", "Torque screwdriver"],
        "materials": ["GFCI receptacle", "AFCI breaker", "12 AWG NM-B cable"],
        "safety": ["De-energize and LOTO", "Never connect GFCI LINE to LOAD side"],
        "steps": ["Identify LINE vs LOAD conductors", "Terminate on LINE side", "Install AFCI breaker at panel", "Energize and functional test", "Trip-test with button and external tester"],
        "rubric": ["Trips on internal test button", "Trips on external tester", "LINE/LOAD correct", "AFCI holds without nuisance trip"],
        "pass_criteria": "All trip tests pass AND no miswire",
        "competencies": ["panels-breakers", "safety-ppe"],
        "skill_points": 45,
        "hours": 3,
    },
    {
        "slug": "branch-circuit-build",
        "title": "Build a 20A Branch Circuit",
        "summary": "From breaker to receptacle, build a complete 20A small-appliance branch circuit in the mobile classroom.",
        "tools": ["Wire strippers", "Drill with hole saws", "Staple gun", "Voltage tester"],
        "materials": ["12 AWG NM-B", "20A breaker", "Duplex receptacles", "4-square and device boxes"],
        "safety": ["LOTO the panel before any work", "Verify de-energized at receptacle with tester"],
        "steps": ["Plan route and hole drilling", "Pull cable through studs", "Make up boxes", "Install devices and cover plates", "Energize, tester-check every outlet"],
        "rubric": ["Receptacle tester passes on every outlet", "Cable stapled per code", "Clean device mounting", "No open splices"],
        "pass_criteria": "All outlets test correct and instructor verifies workmanship",
        "competencies": ["wiring-fundamentals", "panels-breakers"],
        "skill_points": 60,
        "hours": 6,
    },
    {
        "slug": "continuity-voltage-test",
        "title": "Continuity and Voltage Testing",
        "summary": "Perform continuity, voltage, and polarity tests on every circuit in a training panel.",
        "tools": ["Digital multimeter (CAT III 600V)", "Clamp meter", "Known-good test lamp"],
        "materials": ["Training panel with 6 circuits"],
        "safety": ["Test-verify-test procedure on every measurement", "Inspect leads for cracks"],
        "steps": ["Continuity-check each circuit de-energized", "Energize and measure voltage", "Verify polarity at every receptacle", "Log all readings"],
        "rubric": ["Meter function correct for each test", "All readings logged", "Polarity verified", "Test-verify-test followed"],
        "pass_criteria": "All measurements within expected range AND written log submitted",
        "competencies": ["troubleshooting", "tools-equipment"],
        "skill_points": 40,
        "hours": 3,
    },
    {
        "slug": "solar-charge-controller",
        "title": "Install a Solar Charge Controller",
        "summary": "Mount and wire an MPPT charge controller between the PV array and the 48V battery bank.",
        "tools": ["Hydraulic crimper", "Torque wrench", "DMM (CAT III 1000V DC)"],
        "materials": ["MPPT charge controller", "6 AWG PV wire", "Class-T fuse", "DC disconnect"],
        "safety": ["PV cover panels before wiring", "DC arcs do not self-extinguish"],
        "steps": ["Mount controller with airflow clearance", "Wire battery side FIRST (per manufacturer)", "Wire PV side with disconnect open", "Verify polarity with DMM", "Close disconnects in order"],
        "rubric": ["Battery connected before PV", "Correct polarity", "Fuses sized correctly", "Controller programs to battery chemistry"],
        "pass_criteria": "Controller charges on energization AND no polarity reversal",
        "competencies": ["solar-off-grid", "safety-ppe"],
        "skill_points": 55,
        "hours": 4,
    },
    {
        "slug": "solar-panel-mount",
        "title": "Mount and Wire a Solar Panel",
        "summary": "Physically mount a 400W PV module to the roof rail and terminate MC4 connectors.",
        "tools": ["Cordless drill", "Torque wrench", "MC4 crimp tool"],
        "materials": ["400W PV module", "Roof rail and Z-clamps", "MC4 connectors", "10 AWG PV wire"],
        "safety": ["Fall protection on roof work", "Cover panels or work in low light"],
        "steps": ["Inspect module and rail", "Bolt module to rail at torque spec", "Crimp MC4 connectors", "Verify open-circuit voltage with DMM", "Connect to combiner box"],
        "rubric": ["Module torqued correctly", "MC4 connectors latched", "Voc within expected range", "Neat cable management"],
        "pass_criteria": "Module produces rated Voc under sun AND secure mechanical attachment",
        "competencies": ["solar-off-grid", "tools-equipment"],
        "skill_points": 50,
        "hours": 4,
    },
    {
        "slug": "battery-inverter-build",
        "title": "Build a Battery and Inverter System",
        "summary": "Wire a 48V LiFePO4 bank with class-T fuses to a pure-sine inverter.",
        "tools": ["Hydraulic crimper", "Heat gun", "Torque wrench (ft-lbs)", "DMM"],
        "materials": ["48V LiFePO4 bank", "4/0 DC cable", "Class-T fuse & holder", "Pure sine inverter"],
        "safety": ["Remove rings/watches", "Fuse within 7\" of battery positive", "Full face shield recommended"],
        "steps": ["Crimp and heat-shrink cables", "Install class-T fuse at positive", "Land cables on inverter and battery", "Torque to spec", "Commission inverter"],
        "rubric": ["Class-T placement correct", "Crimps pull-tested", "Torque at spec", "Inverter produces 120V AC clean"],
        "pass_criteria": "Inverter runs a load AND fuse placement verified by instructor",
        "competencies": ["solar-off-grid", "wiring-fundamentals"],
        "skill_points": 65,
        "hours": 6,
    },
    {
        "slug": "loto-real-equipment",
        "title": "Perform LOTO on Real Equipment",
        "summary": "Execute a complete six-step LOTO on a motor disconnect, witnessed by a second qualified person.",
        "tools": ["Personal padlock and tag", "Voltage tester (known good)", "Class 0 gloves"],
        "materials": ["Motor disconnect (de-energized)", "Tag kit"],
        "safety": ["Complete PPE before approach", "Test-verify-test every time"],
        "steps": ["Notify affected workers", "Shut off disconnect", "Lock and tag with your personal lock", "Verify dead with tester (test-verify-test)", "Release stored energy", "Try to start — confirm dead"],
        "rubric": ["All six steps performed in order", "Personal lock only", "Test-verify-test followed", "Try-start performed"],
        "pass_criteria": "Instructor and witnessing partner both sign off",
        "competencies": ["safety-ppe", "professionalism"],
        "skill_points": 50,
        "hours": 3,
    },
]
