#!/bin/bash
# Script to help generate and optimize creator images
# Usage: ./scripts/generate-creator-images.sh

set -e

CREATORS_DIR="public/images/creators"
PROMPTS_FILE="IMAGE_PROMPTS.md"

echo "🎨 WAI Creator Image Generation Helper"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if directory exists
if [ ! -d "$CREATORS_DIR" ]; then
    echo "✅ Creating $CREATORS_DIR directory..."
    mkdir -p "$CREATORS_DIR"
fi

echo "📋 Image Generation Prompts:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  POET & HEALER"
echo "   Portrait of a Black woman poet in her late 30s, sitting at a writing desk"
echo "   surrounded by candles and books, warm natural lighting from a window,"
echo "   expression of peaceful focus, wearing earth tones, spiritual and"
echo "   contemplative atmosphere, professional photography"
echo ""
echo "2️⃣  VISUAL ARTIST"
echo "   Black male artist in his 40s in a vibrant studio surrounded by colorful"
echo "   abstract paintings, holding a paintbrush, natural sunlight streaming in,"
echo "   creative energy, professional studio setting, warm color palette,"
echo "   confident expression, professional photography"
echo ""
echo "3️⃣  WELLNESS INSTRUCTOR"
echo "   Black woman wellness instructor leading a meditation/yoga session with"
echo "   students visible in background, warm indoor lighting, peaceful demeanor,"
echo "   wearing comfortable spiritual clothing, authentic classroom setting"
echo ""
echo "4️⃣  MUSIC PRODUCER"
echo "   Black male music producer working at a professional recording studio,"
echo "   wearing headphones, hands on mixing board with colorful displays,"
echo "   creative focus, modern studio environment, strong confidence"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 Where to go:"
echo "   • DALL-E 3: https://chat.openai.com/chat (ChatGPT Plus)"
echo "   • Midjourney: https://www.midjourney.com/"
echo "   • Stable Diffusion: https://huggingface.co/spaces/stabilityai/SDXL"
echo ""
echo "💾 After generating, place images here:"
echo "   $CREATORS_DIR/"
echo ""
echo "🖼️  Expected filenames:"
echo "   • creator-1-poet.jpg"
echo "   • creator-2-artist.jpg"
echo "   • creator-3-healer.jpg"
echo "   • creator-4-musician.jpg"
echo ""
echo "📦 Optimize with:"
echo "   • TinyPNG: https://tinypng.com"
echo "   • ImageOptim: https://imageoptim.com"
echo "   • ffmpeg: ffmpeg -i input.jpg -c:v libwebp -q:v 80 output.webp"
echo ""
echo "✅ Once images are ready:"
echo "   1. Place them in $CREATORS_DIR/"
echo "   2. Test locally: npm run dev"
echo "   3. Commit: git add frontend/public/images/ && git commit -m 'feat: add creator images'"
echo ""
